import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '@components/Banner/Banner'
import Navbar from '@components/Navbar/Navbar'
import SectionCards from '@components/SectionsCards/SectionCards'
import videos from '@lib/videos'

export async function getServerSideProps() {
  const disneyVideos = videos()
  return {
    props: {disneyVideos}
  }
}


export default function Home({disneyVideos}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Netlix-Tube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        username='cristiand395@gmail.com'/>
      <Banner
        title='Dont look up'
        subtitle='Leonardo Di Caprio Movie'
        imgUrl='/static/clifford.webp'/>
      <div className={styles.sectionWrapper}>
        <SectionCards
          videos = {disneyVideos}
          title='Popular'
          size='large'/>
      </div>
    </div>
  )
}
