import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '@components/Banner/Banner'
import Navbar from '@components/Navbar/Navbar'
import SectionCards from '@components/SectionsCards/SectionCards'
import {getVideos} from '@lib/videos'

export async function getServerSideProps() {
  const netflixVideos = await getVideos('netflix trailers')
  const disneyVideos = await getVideos('disney trailers')
  const techVideos = await getVideos('smartphones reviwes')

  return {
    props: {
      netflixVideos, 
      disneyVideos,
      techVideos
    }
  }
}

export default function Home({netflixVideos, disneyVideos, techVideos}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Netlix-Tube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Navbar
        username='cristiand395@gmail.com'/>
        <Banner
          title='Dont look up'
          subtitle='Leonardo Di Caprio Movie'
          imgUrl='/static/clifford.webp'/>
        <div className={styles.sectionWrapper}>
          <SectionCards
            videos = {netflixVideos}
            title='Netflix'
            size='large'/>
          <SectionCards
            videos = {disneyVideos}
            title='Disney'
            size='medium'/>
          <SectionCards
            videos = {techVideos}
            title='Smartphones'
            size='small'/>
        </div>  
      </div>
    </div>
  )
}
